# -*- coding: utf-8 -*-
"""def3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzu_rfG2wkvG4pMkMjqwvxg312zGYqDl
"""

# -*- coding: utf-8 -*-
"""
On the Asymptotic Width of the Poeschl-Teller Ground State
==========================================================

Salvatore Pennacchio - Independent Researcher - October 2026

This script verifies the exact form of the ground state of the
one-dimensional Schroedinger operator

    H(mu) = -d^2/dr^2 - 2 mu sech^2(r),    mu > 0,

and the asymptotic behavior of its effective width

    ell^2_op(mu) = <r^4> / <r^2>,

where <r^n> denotes the n-th moment of |psi_0(r)|^2.

Main results (proved in the accompanying note):

    psi_0(r) = sech^{a(mu)}(r),
    a(mu)    = ( sqrt(1 + 8 mu) - 1 ) / 2,
    E_0(mu)  = -a(mu)^2,

    ell^2_op(mu) ~ 3 / ( 2 a(mu) )   as mu -> infinity,

    a(mu) * ell^2_op(mu) -> 3/2.

The coefficient 3/2 is the ratio between the fourth and second
moments of a Gaussian distribution. It has no relation to the
golden ratio.

Output sections:
    (1)  Setup
    (2a) Numerical vs analytical comparison of ell^2_op(mu)
    (2b) Consistency test: ell^2_op(mu, eps) = 4 ell^2_gas(k, beta)
    (3)  Convergence of a(mu) * ell^2_op(mu) to 3/2

References:
    G. Poeschl, E. Teller, Z. Phys. 83, 143 (1933).
    L. D. Landau, E. M. Lifshitz, Quantum Mechanics, 3rd ed.
    S. Pennacchio, technical note (2026).
"""

import numpy as np
from scipy.linalg import eigh
from scipy.special import lambertw
from mpmath import mp, mpf, zeta, diff as mpdiff, log, quad, cosh, sqrt
import time

# ----------------------------------------------------------------------
# Global settings
# ----------------------------------------------------------------------

mp.dps = 40                            # decimal digits for mpmath
PHI = (1.0 + np.sqrt(5.0)) / 2.0       # golden ratio (used only in the AA lattice)
LINE = "=" * 74


# ----------------------------------------------------------------------
# Section 1 : Setup
# ----------------------------------------------------------------------

print(LINE)
print(" SECTION 1 - SETUP")
print(LINE)
print()

# ---------- Gentile gas side ------------------------------------------

def E_gas(beta, k):
    """Mean energy of the Gentile gas at inverse temperature beta."""
    beta = mpf(beta)
    if k == np.inf:
        return float(-mpdiff(zeta, beta) / zeta(beta))
    return float(-mpdiff(zeta, beta) / zeta(beta)
                 + (k + 1) * mpdiff(zeta, (k + 1) * beta) / zeta((k + 1) * beta))


def c_k(k):
    """Entropic constant c_k = 1 - ln zeta(k+1)."""
    return 1.0 if k == np.inf else 1.0 - float(log(zeta(k + 1)))


def alpha_LW(beta, k):
    """Lambert-W commutation factor alpha(k, beta)."""
    E = E_gas(beta, k)
    if E <= 0:
        return np.nan
    return lambertw(E * np.exp(E + c_k(k))).real / E


def ell2_gas(beta, k):
    """Effective gas length ell^2_gas = 1 / (pi alpha)."""
    a = alpha_LW(beta, k)
    if np.isnan(a):
        return np.nan, np.nan
    return 1.0 / (np.pi * a), a


# ---------- Schroedinger operator: numerical discretization ----------

N      = 600
r_max  = 25.0
r      = np.linspace(-r_max, r_max, N)
dr     = r[1] - r[0]
alpha_AA = 1.0 / PHI

_main   = 2.0 / dr**2 * np.ones(N)
_off    = -1.0 / dr**2 * np.ones(N - 1)
H_kin   = np.diag(_main) + np.diag(_off, 1) + np.diag(_off, -1)
sech2_arr = 1.0 / np.cosh(r)**2
cos_arr   = np.cos(2 * np.pi * alpha_AA * r)


def ell2_op_num(mu, eps=0.0):
    """Effective width ell^2_op(mu, eps) from the discretized Hamiltonian."""
    V = eps * cos_arr - 2 * mu * sech2_arr
    H = H_kin + np.diag(np.clip(V, -1e6, 1e6))
    E, psi = eigh(H)
    psi0 = psi[:, 0] / np.sqrt(np.sum(psi[:, 0]**2) * dr)
    r2 = np.sum(r**2 * psi0**2) * dr
    r4 = np.sum(r**4 * psi0**2) * dr
    return r4 / r2 if r2 > 1e-12 else np.nan


# ---------- Schroedinger operator: analytical (Poeschl-Teller) --------

def a_of_mu(mu):
    """Exponent of the ground state: a(mu) = (sqrt(1 + 8 mu) - 1) / 2."""
    return (-1.0 + np.sqrt(1.0 + 8.0 * mu)) / 2.0


def I2_anal(a):
    """<r^2> for the density sech^{2a}(r), computed with mpmath."""
    a_mp = mpf(a)
    if a_mp <= mpf("0.5"):
        return np.nan
    f = lambda x: x**2 / cosh(x)**(2 * a_mp)
    peak = 1 / sqrt(2 * a_mp)
    return 2 * quad(f, [0, peak, mpf(10), mpf("inf")])


def I4_anal(a):
    """<r^4> for the density sech^{2a}(r), computed with mpmath."""
    a_mp = mpf(a)
    if a_mp <= mpf("0.5"):
        return np.nan
    f = lambda x: x**4 / cosh(x)**(2 * a_mp)
    peak = 1 / sqrt(2 * a_mp)
    return 2 * quad(f, [0, peak, mpf(10), mpf("inf")])


def ell2_op_anal(mu):
    """Analytical ell^2_op(mu) with the corrected exponent a(mu)."""
    a = a_of_mu(mu)
    if a <= 0.5:
        return np.nan
    return float(I4_anal(a) / I2_anal(a))


print(f"  Operator grid:    N = {N},  r_max = {r_max}")
print(f"  Aubry-Andre alpha = 1/Phi = {alpha_AA:.10f}")
print(f"  Ground state:     psi_0(r) = sech^{{a(mu)}}(r)")
print(f"  Exponent:         a(mu) = (sqrt(8 mu + 1) - 1) / 2")
print()


# ----------------------------------------------------------------------
# Section 2a : Numerical vs analytical comparison
# ----------------------------------------------------------------------

print(LINE)
print(" SECTION 2a - NUMERICAL vs ANALYTICAL ell^2_op(mu)")
print(LINE)
print()
print(f"  {'mu':>6} {'a(mu)':>8} {'ell^2_num':>14} {'ell^2_anal':>14} "
      f"{'diff %':>10} {'a * ell^2':>10}")
print("  " + "-" * 66)

for mu in [1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 20.0]:
    en = ell2_op_num(mu, 0.0)
    ea = ell2_op_anal(mu)
    a  = a_of_mu(mu)
    diff = abs(en - ea) / en * 100.0 if en > 0 else 0.0
    print(f"  {mu:>6.2f} {a:>8.4f} {en:>14.8f} {ea:>14.8f} "
          f"{diff:>10.4f} {a * ea:>10.6f}")


# ----------------------------------------------------------------------
# Section 2b : Consistency test on the operator lattice
# ----------------------------------------------------------------------

print()
print(LINE)
print(" SECTION 2b - TEST: ell^2_op(mu, eps) = 4 ell^2_gas(k, beta)")
print(LINE)
print()

t0 = time.time()
mu_grid  = np.linspace(0.5, 60, 40)
eps_grid = np.array([0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 12.0])

table = np.zeros((len(mu_grid), len(eps_grid)))
for i, mu in enumerate(mu_grid):
    for j, eps in enumerate(eps_grid):
        table[i, j] = ell2_op_num(mu, eps)

print(f"  Precomputed grid {len(mu_grid)} x {len(eps_grid)} "
      f"in {time.time() - t0:.1f} s")
print()


def find_best_mu_eps(target):
    diff = np.abs(table - target)
    i, j = np.unravel_index(np.argmin(diff), diff.shape)
    return mu_grid[i], eps_grid[j], table[i, j]


print(f"  {'k':>5} {'beta':>6} {'4 ell^2_gas':>12} {'mu*':>10} {'eps*':>8} "
      f"{'ell^2_op':>12} {'err %':>10}")
print("  " + "-" * 70)

for k in [1, 2, 5, 10]:
    for beta in [1.05, 1.5, 2.0, 3.0, 5.0]:
        ell2g, _ = ell2_gas(beta, k)
        target = 4.0 * ell2g
        mu, eps, ell2o = find_best_mu_eps(target)
        err = abs(ell2o - target) / target * 100.0
        print(f"  {k:>5} {beta:>6.2f} {target:>12.6f} {mu:>10.3f} {eps:>8.3f} "
              f"{ell2o:>12.6f} {err:>10.4f}")
    print()


# ----------------------------------------------------------------------
# Section 3 : Convergence of a(mu) ell^2_op(mu) to 3/2
# ----------------------------------------------------------------------

print(LINE)
print(" SECTION 3 - ASYMPTOTIC: a(mu) ell^2_op(mu) -> 3/2")
print(LINE)
print()
print(f"  {'mu':>8} {'a * ell^2':>14} {'3/2 - a * ell^2':>18}")
print("  " + "-" * 44)

for mu in [10, 20, 50, 100, 200, 500, 1000]:
    ea = ell2_op_anal(mu)
    a  = a_of_mu(mu)
    prod = a * ea
    print(f"  {mu:>8.1f} {prod:>14.8f} {1.5 - prod:>18.8f}")

print()
print("  Derivation: for mu large, psi_0 is approximately Gaussian")
print("  with variance sigma^2 = 1/(2a). Gaussian moments give")
print("      <r^2> = sigma^2,   <r^4> = 3 sigma^4,")
print("  hence")
print("      ell^2_op = <r^4>/<r^2> = 3 sigma^2 = 3/(2a).")
print("  The coefficient 3 is the Gaussian fourth-moment coefficient;")
print("  the coefficient 2 arises from sigma^2 = 1/(2a).")
print()

print(LINE)
print(" END OF SCRIPT")
print(LINE)