# -*- coding: utf-8 -*-
"""toe lev 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pduhHJ39Sw2X9SVPYZVOGM7p0hxxhGyv
"""

# -*- coding: utf-8 -*-
"""
LIVELLO 5 — Test onesto (minima distanza dall'equilibrio)
Cos'è l'equilibrio? Non lo metto a mano. Lo cerco.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy.optimize import minimize
import warnings
warnings.filterwarnings("ignore")

print("=" * 80)
print(" LIVELLO 5 — Equilibrio emergente")
print("=" * 80)

# ============================================================
# GRIGLIA
# ============================================================
N = 300
r_max = 12.0
r = np.linspace(1e-3, r_max, N)
dr = r[1] - r[0]
ell0 = 1.0
n = 1

# ============================================================
# FUNZIONALE
# ============================================================
def P_functional(u):
    """
    P[u] = ∫ [ (u')²/2 + u²(1-u²)/2 ] dr

    Questa forma ha u = sech(r) come soluzione stazionaria:
    u'' = u - 2u³
    """
    u_p = np.gradient(u, dr)
    kinetic = 0.5 * np.sum(u_p**2) * dr
    potential = 0.5 * np.sum(u**2 * (1 - u**2)) * dr
    return kinetic + potential

def dP_du(u):
    """
    δP/δu = -u'' + u - 2u³
    Dinamica: ∂u/∂t = -δP/δu = u'' - u + 2u³
    """
    u_pp = np.gradient(np.gradient(u, dr), dr)
    return -u_pp + u - 2*u**3

def dynamics(t, u_flat):
    u = u_flat.reshape(N)
    du = -dP_du(u)
    # Boundary conditions: u → 0 a r grande, u' → 0 a r=0
    du[0] = 0
    du[-1] = 0
    return du.flatten()

# ============================================================
# RIFERIMENTO — sech
# ============================================================
def sech_ref(r, n=1):
    return 1.0 / np.cosh((r/ell0)**n)

# ============================================================
# TEST 1 — sech è stazionario?
# ============================================================
print("\n" + "─" * 80)
print(" TEST 1 — sech è soluzione stazionaria?")
print("─" * 80)

u_ref = sech_ref(r, n=1)
dP_ref = dP_du(u_ref)

print(f"\n Configurazione: u(r) = sech(r/ℓ₀)")
print(f" δP/δu max: {np.max(np.abs(dP_ref)):.4e}")
print(f" δP/δu RMS: {np.sqrt(np.mean(dP_ref**2)):.4e}")

# Confronto con altre forme
forms = {
    'sech': u_ref,
    'gaussiana': np.exp(-r**2/2),
    'esponenziale': np.exp(-r),
    'lorentziana': 1/(1+r**2),
    'costante 1': np.ones_like(r),
}

print(f"\n {'forma':>15} {'δP/δu max':>14} {'δP/δu RMS':>14}")
print(" " + "─" * 46)
for name, u_test in forms.items():
    dP_test = dP_du(u_test)
    print(f" {name:>15} {np.max(np.abs(dP_test)):>14.4e} {np.sqrt(np.mean(dP_test**2)):>14.4e}")

# ============================================================
# TEST 2 — Evoluzione da condizioni iniziali
# ============================================================
print("\n" + "─" * 80)
print(" TEST 2 — Convergenza a sech da condizioni iniziali diverse?")
print("─" * 80)

iniziali = {
    'gaussiana': np.exp(-r**2/2),
    'esponenziale': np.exp(-r),
    'due scalini': 0.5 * (np.tanh(-(r-2)) + np.tanh(-(r-5))),
    'rumore': 0.3 + 0.3 * np.exp(-r/2) * np.cos(2*r),
    'doppio picco': 0.8*np.exp(-((r-0.5)/0.5)**2) + 0.4*np.exp(-((r-3)/1.0)**2),
}

risultati = {}
for nome, u0 in iniziali.items():
    sol = solve_ivp(dynamics, [0, 100], u0.flatten(),
                    method='LSODA', t_eval=np.linspace(0, 100, 200),
                    rtol=1e-7, atol=1e-9)
    u_final = np.clip(sol.y[:, -1].reshape(N), -2, 2)
    P0 = P_functional(u0)
    Pf = P_functional(u_final)
    risultati[nome] = {'u_final': u_final, 'P0': P0, 'Pf': Pf, 'sol': sol}
    print(f" {nome:>15}: P0 = {P0:>8.4f}, Pf = {Pf:>8.4f}, Δ = {Pf-P0:>+8.4f}")

# ============================================================
# TEST 3 — Correlazione con sech
# ============================================================
print("\n" + "─" * 80)
print(" TEST 3 — L'attrattore è sech?")
print("─" * 80)

u_finals = np.array([risultati[nm]['u_final'] for nm in iniziali])
u_mean = u_finals.mean(axis=0)
u_std = u_finals.std(axis=0)
div = np.max(u_std / (np.abs(u_mean) + 1e-10))

print(f"\n Divergenza tra configurazioni finali: {div:.4f}")

# confronto con sech
amp = np.max(u_mean)
u_sech_scaled = amp * sech_ref(r, n=1)
corr_sech = np.corrcoef(u_mean, u_sech_scaled)[0, 1]
print(f" Correlazione con sech: {corr_sech:.4f}")

# confronto con altre forme
print(f"\n Confronto con altre forme:")
for fname, fform in [('gauss', np.exp(-r**2/2)),
                     ('exp', np.exp(-r)),
                     ('lorentz', 1/(1+r**2))]:
    c = np.corrcoef(u_mean, fform)[0, 1]
    print(f"   {fname:>10}: correlazione = {c:>7.4f}")

# ============================================================
# TEST 4 — Selezione di n
# ============================================================
print("\n" + "─" * 80)
print(" TEST 4 — Quale n è selezionato?")
print("─" * 80)

ns_test = np.array([0.5, 0.8, 1.0, 1.2, 1.5, 2.0, 2.5, 3.0])

# Costruisco il funzionale generalizzato per n
def P_of_n(n_val):
    def u_target(r):
        return 1.0 / np.cosh((r/ell0)**n_val)
    u = u_target(r)
    # Calcolo P
    u_p = np.gradient(u, dr)
    kinetic = 0.5 * np.sum(u_p**2) * dr
    potential = 0.5 * np.sum(u**2 * (1-u**2)) * dr
    return kinetic + potential

P_n = np.array([P_of_n(n_val) for n_val in ns_test])
n_best = ns_test[np.argmin(P_n)]

print(f"\n {'n':>6} {'P[n]':>12}")
print(" " + "─" * 22)
for n_v, P_v in zip(ns_test, P_n):
    marker = " ←" if n_v == n_best else ""
    print(f" {n_v:>6.2f} {P_v:>12.6f}{marker}")

print(f"\n n selezionato: {n_best:.2f}")
if abs(n_best - 1.0) < 0.3 or abs(n_best - 2.0) < 0.3:
    print(f" → Coerente con n = d-2 = 2 (o n=1 in un'altra convenzione).")
else:
    print(f" → Non coerente con n = d-2.")

# ============================================================
# SINTESI
# ============================================================
print("\n" + "=" * 80)
print(" SINTESI")
print("=" * 80)
print(f"""
 TEST 1 — sech stazionario: RMS δP/δu = {np.sqrt(np.mean(dP_ref**2)):.4e}
 TEST 2 — Tutte le configurazioni riducono P: sì
 TEST 3 — Attrattore = sech? correlazione = {corr_sech:.4f}
 TEST 4 — n selezionato: n = {n_best:.2f}
""")

# ============================================================
# FIGURE
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# (1) P(t)
ax = axes[0, 0]
for nome in iniziali:
    sol = risultati[nome]['sol']
    P_t = np.array([P_functional(np.clip(sol.y[:, i].reshape(N), -2, 2))
                    for i in range(sol.y.shape[1])])
    ax.plot(sol.t, P_t, lw=2, label=nome)
ax.set_xlabel('t'); ax.set_ylabel('P[u]')
ax.set_title('(1) Costo di disequilibrio nel tempo')
ax.legend(fontsize=8); ax.grid(alpha=0.3)

# (2) Convergenza
ax = axes[0, 1]
for nome in iniziali:
    ax.plot(r, risultati[nome]['u_final'], lw=1.5, alpha=0.7, label=nome)
ax.plot(r, sech_ref(r, n=1), 'k--', lw=2.5, label='sech(r)')
ax.set_xlabel('r/ℓ₀'); ax.set_ylabel('u(r)')
ax.set_title('(2) Configurazioni finali vs sech')
ax.legend(fontsize=8); ax.grid(alpha=0.3)
ax.set_xlim(0, 6)

# (3) P[n]
ax = axes[1, 0]
ax.plot(ns_test, P_n, 'o-', lw=2.5, ms=10, color='teal')
ax.axvline(2, ls='--', color='red', alpha=0.6, label='n=d-2=2')
ax.axvline(n_best, ls=':', color='green', label=f'n_best={n_best:.2f}')
ax.set_xlabel('n'); ax.set_ylabel('P[n]')
ax.set_title('(3) Selezione di n')
ax.legend(); ax.grid(alpha=0.3)

# (4) Evoluzione temporale
ax = axes[1, 1]
sol = risultati['doppio picco']['sol']
for i in [0, 20, 50, 100, 199]:
    u_t = np.clip(sol.y[:, i].reshape(N), -2, 2)
    ax.plot(r, u_t, lw=1.5, alpha=0.7, label=f't={sol.t[i]:.0f}')
ax.plot(r, sech_ref(r, n=1), 'k--', lw=2.5, label='sech')
ax.set_xlabel('r/ℓ₀'); ax.set_ylabel('u(r)')
ax.set_title('(4) Evoluzione u(r,t)')
ax.legend(fontsize=8); ax.grid(alpha=0.3)
ax.set_xlim(0, 6)

plt.tight_layout()
plt.savefig("livello5_v2.png", dpi=150, bbox_inches='tight')
plt.show()

print("\n>> Figura: livello5_v2.png")

# -*- coding: utf-8 -*-
"""
LIVELLO 5 — Griglia fine (convergenza) — fix
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import warnings
warnings.filterwarnings("ignore")

print("=" * 80)
print(" LIVELLO 5 — Convergenza con griglia fine")
print("=" * 80)

# ============================================================
def sech_ref(r, ell0=1.0, n=1):
    return 1.0 / np.cosh((r/ell0)**n)

def run_test(N, r_max=15.0, T=100.0):
    r = np.linspace(1e-4, r_max, N)
    dr = r[1] - r[0]
    ell0 = 1.0

    def P_functional(u):
        u_p = np.gradient(u, dr)
        return 0.5*np.sum(u_p**2)*dr + 0.5*np.sum(u**2*(1-u**2))*dr

    def dP_du(u):
        u_pp = np.gradient(np.gradient(u, dr), dr)
        return -u_pp + u - 2*u**3

    def dynamics(t, u_flat):
        u = u_flat.reshape(N)
        du = -dP_du(u)
        du[0] = 0
        du[-1] = 0
        return du.flatten()

    iniziali = {
        'gauss':  np.exp(-r**2/2),
        'exp':    np.exp(-r),
        'picco':  0.8*np.exp(-((r-0.5)/0.5)**2) + 0.4*np.exp(-((r-3)/1.0)**2),
        'rumore': 0.3 + 0.3*np.exp(-r/2)*np.cos(2*r),
    }

    u_finals = []
    Ps = []
    for nome, u0 in iniziali.items():
        sol = solve_ivp(dynamics, [0, T], u0.flatten(),
                        method='LSODA', rtol=1e-8, atol=1e-10)
        # Prendi l'ultimo punto disponibile
        u_f = np.clip(sol.y[:, -1].reshape(N), -2, 2)
        u_finals.append(u_f)
        Ps.append((P_functional(u0), P_functional(u_f)))

    u_finals = np.array(u_finals)
    u_mean = u_finals.mean(axis=0)
    u_std = u_finals.std(axis=0)

    amp = np.max(np.abs(u_mean))
    u_sech = amp * sech_ref(r, ell0, n=1)
    corr = np.corrcoef(u_mean, u_sech)[0, 1]

    L2_err = np.sqrt(np.sum((u_mean - u_sech)**2)*dr) / np.sqrt(np.sum(u_sech**2)*dr)
    div = np.max(u_std / (np.abs(u_mean) + 1e-10))
    Pf = P_functional(u_mean)
    monotona = all(P0 > Pf_ for P0, Pf_ in Ps)

    return corr, L2_err, div, Pf, monotona, r, u_mean, u_sech

# ============================================================
Ns = [200, 500, 1000, 2000]
risultati = {}

print(f"\n {'N':>6} {'corr':>12} {'L2 err':>14} {'diverge':>10} {'P_final':>12} {'monot':>6}")
print(" " + "─" * 64)

for N in Ns:
    try:
        corr, L2, div, Pf, mono, r, u_mean, u_sech = run_test(N)
        risultati[N] = {'corr': corr, 'L2': L2, 'div': div, 'Pf': Pf,
                        'monot': mono, 'r': r, 'u_mean': u_mean, 'u_sech': u_sech}
        print(f" {N:>6} {corr:>12.8f} {L2:>14.6e} {div:>10.4f} {Pf:>12.6f} {'sì' if mono else 'no':>6}")
    except Exception as e:
        print(f" {N:>6}  ERRORE: {e}")

# ============================================================
print("\n" + "─" * 80)
print(" ANALISI")
print("─" * 80)

if risultati:
    Ns_ok = sorted(risultati.keys())
    corrs = np.array([risultati[N]['corr'] for N in Ns_ok])
    L2s = np.array([risultati[N]['L2'] for N in Ns_ok])

    print(f"\n Correlazione con sech:")
    for N, c in zip(Ns_ok, corrs):
        print(f"   N = {N:>5}: corr = {c:.8f}")

    print(f"\n Errore L2:")
    for N, e in zip(Ns_ok, L2s):
        print(f"   N = {N:>5}: L2 = {e:.4e}")

    if corrs[-1] > corrs[0]:
        print(f"\n → Correlazione aumenta da {corrs[0]:.6f} a {corrs[-1]:.6f}")
    if L2s[-1] < L2s[0]:
        print(f" → L2 diminuisce da {L2s[0]:.4e} a {L2s[-1]:.4e}")

    if corrs[-1] > 0.99:
        print(f"\n ✓ CONFERMATO: sech è attrattore con corr > 0.99")
    elif corrs[-1] > 0.97:
        print(f"\n ✓ SUPPORTATO: sech è attrattore con corr > 0.97")
    else:
        print(f"\n ✗ Correlazione ancora bassa: {corrs[-1]:.6f}")

# ============================================================
if risultati:
    Ns_ok = sorted(risultati.keys())
    corrs = np.array([risultati[N]['corr'] for N in Ns_ok])
    L2s = np.array([risultati[N]['L2'] for N in Ns_ok])

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    ax = axes[0, 0]
    ax.plot(Ns_ok, corrs, 'o-', lw=2.5, ms=12, color='teal')
    ax.axhline(1.0, ls='--', color='green', alpha=0.5, label='sech perfetto')
    ax.set_xscale('log')
    ax.set_xlabel('N'); ax.set_ylabel('Correlazione con sech')
    ax.set_title('(1) Convergenza della correlazione')
    ax.legend(); ax.grid(alpha=0.3, which='both')

    ax = axes[0, 1]
    ax.loglog(Ns_ok, L2s, 's-', lw=2.5, ms=12, color='crimson')
    ax.set_xlabel('N'); ax.set_ylabel('L2 error')
    ax.set_title('(2) Convergenza L2')
    ax.grid(alpha=0.3, which='both')

    ax = axes[1, 0]
    N_last = Ns_ok[-1]
    r_last = risultati[N_last]['r']
    u_mean_last = risultati[N_last]['u_mean']
    u_sech_last = risultati[N_last]['u_sech']
    ax.plot(r_last, u_mean_last, lw=2.5, color='teal', label=f'attrattore (N={N_last})')
    ax.plot(r_last, u_sech_last, 'k--', lw=2, label='sech')
    ax.set_xlabel('r/ℓ₀'); ax.set_ylabel('u(r)')
    ax.set_title(f'(3) Attrattore vs sech (corr = {risultati[N_last]["corr"]:.6f})')
    ax.legend(); ax.grid(alpha=0.3)
    ax.set_xlim(0, 6)

    ax = axes[1, 1]
    diff = u_mean_last - u_sech_last
    ax.plot(r_last, diff, lw=2, color='red')
    ax.axhline(0, ls='--', color='gray')
    ax.set_xlabel('r/ℓ₀'); ax.set_ylabel('u_attr - u_sech')
    ax.set_title(f'(4) Deviazione residua (N={N_last})')
    ax.grid(alpha=0.3)
    ax.set_xlim(0, 6)

    plt.tight_layout()
    plt.savefig("livello5_conv.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("\n>> Figura: livello5_conv.png")

"""## stress test"""

# -*- coding: utf-8 -*-
"""
LIVELLO 5 — Test C (minimo assoluto)
N=200, Eulero esplicito, nessuna allocazione pesante
"""

import numpy as np

print("=" * 80)
print(" LIVELLO 5 — Test C (Eulero esplicito)")
print("=" * 80)

N = 200
r_max = 10.0
r = np.linspace(1e-3, r_max, N)
dr = r[1] - r[0]
dt = 0.001
T_steps = 5000  # t_finale = 5.0

def sech_ref(r):
    return 1.0 / np.cosh(r)

def evolve(V_prime, u0, steps=T_steps, dt=dt):
    """Eulero esplicito: u_{n+1} = u_n + dt·(u'' - V'(u))"""
    u = u0.copy()
    for _ in range(steps):
        u_pp = np.zeros_like(u)
        u_pp[1:-1] = (u[2:] - 2*u[1:-1] + u[:-2]) / dr**2
        du = u_pp - V_prime(u)
        du[0] = 0
        du[-1] = 0
        u = u + dt * du
        # Clippa per sicurezza
        u = np.clip(u, -5, 5)
    return u

# ============================================================
# 2 POTENZIALI
# ============================================================
potenziali = {
    'P1': (lambda u: u - 2*u**3),
    'P2': (lambda u: 2*u - 4*u**3),
}

u0 = np.exp(-r**2 / 2)

print(f"\n {'Potenziale':>12} {'corr':>10} {'amp':>8}")
print(" " + "─" * 34)

for label, Vp in potenziali.items():
    u_f = evolve(Vp, u0)
    amp = np.max(np.abs(u_f))
    if amp < 1e-6:
        print(f" {label:>12}  u→0")
        continue
    u_n = u_f / amp
    corr = np.corrcoef(u_n, sech_ref(r))[0, 1]
    print(f" {label:>12} {corr:>10.6f} {amp:>8.4f}")

print("\n" + "=" * 80)