"""
Genuinely variational replacement for scan_ising.py.

scan_ising.py's ansatz (CX(q,q+1)-RZ(q+1,1.2)-CX(q,q+1) per bond, then
RX(q, 0.6*g) per qubit) never minimizes any energy -- it only ever measures
<ZZ> at a hardcoded RZ angle and a heuristic RX mapping. This script keeps
the EXACT SAME circuit structure (same gate order, same shared-parameter
convention: one theta for every RZ, one phi for every RX) but makes theta
and phi trainable, and minimizes the real TFIM energy
E(theta,phi;g) = -sum_i <Z_i Z_{i+1}> - g*sum_i <X_i> at every g via Adam.

--- A structural finding this optimization exposes (verified twice below,
analytically and against finite differences) ---

1. theta (the RZ angle) has EXACTLY ZERO effect on any observable, for any
   value, at any g. CX(q,q+1)-RZ(q+1,theta)-CX(q,q+1) is diagonal in the
   computational basis (it implements exp(-i*theta/2 Z_q Z_{q+1}) up to a
   global phase), and it is applied to |0...0>, which is already a
   computational basis state -- i.e. an eigenstate of every Z_qZ_{q+1}. A
   diagonal gate applied to a single eigenstate produces only a global
   phase, which is unobservable and washes out of every expectation value
   computed afterward, RX layer included. Confirmed: dE/dtheta = 0 to
   float64 noise (~1e-14) via exact parameter-shift, everywhere on the
   g-grid below.

2. Because of (1), the ONLY parameter that can matter is phi. But RX(phi)
   is generated by X, so it commutes with every X_q: <X_q> is invariant
   under RX(phi) applied to that same qubit. Since the initial state
   |0...0> has <X_q> = 0 for every q, and the RZ layer contributes nothing
   (point 1), <X_q> = 0 identically for this ansatz -- for ANY theta, phi,
   at ANY g. Confirmed numerically below (sum_q <X_q> ~ 1e-17 for
   phi=1.0, theta=1.2).

Together, (1)+(2) mean E(theta,phi;g) = -(N-1)*cos(phi)^2 for this exact
circuit -- g never appears in the energy at all. Real energy minimization
therefore converges to the SAME phi*=0 (maximizing cos^2) regardless of g,
giving a constant <ZZ>=1 and E=-(N-1) for every g. scan_ising.py's
g-dependence (<ZZ> = cos(0.6g)^2, matching its own curve to float64
precision -- see ising_exact_verification.py's g=1.309 check) came
entirely from the arbitrary, non-variational phi=0.6*g mapping, not from
any energy-driven response to the transverse field. A truly variational
treatment of the SAME ansatz shows it cannot represent the transverse-field
Hamiltonian's g-dependence at all, by this simple commutation argument --
not "close but imperfect", a hard structural ceiling. This is reported
plainly below rather than worked around (no gate reordering, no per-qubit
parameters -- both would break comparability with the original circuit).

--- Implementation notes ---

Gradients are computed via the exact chain-rule Parameter-Shift Rule
(same technique as vqe_silicon_molecular_optimized.py / vqe_jax_grad.py),
not jax.grad: reverse-mode autodiff through a vmapped 12-qubit (4096-dim)
circuit batched over a few hundred g-points was tried first and hit real
OOM on this machine (RESOURCE_EXHAUSTED requesting ~12GB at 400 points,
on an 8GB-RAM host) -- PSR needs only forward passes, so its memory stays
O(batch*dim) instead of whatever reverse-mode's tape needed here.

DenseSVSimulator.run_batch_jit itself is also avoided in the hot loop: it
builds a fresh jax.jit(jax.vmap(...)) closure on every single call, so
back-to-back calls with an IDENTICAL shape get no compilation caching at
all (verified: repeated calls all took ~34s, no warm speedup). This script
instead builds the same jax.lax.scan-based state-preparation function ONCE
at module scope, wrapped in a single persistent @jax.jit, reusing the
package's own `_compile_and_run_circuit_jit` (compiler.py) and
QuantumTranspiler (the same building blocks dense_evolution.autodiff.
circuit_to_energy_fn uses) -- giving real compile-once/reuse caching
across every Adam epoch.

theta is fixed at scan_ising.py's original 1.2 for the whole sweep (not
optimized -- point (1) above makes that provably pointless) and is not
given a PSR row at all, since its gradient is 0.
"""

import pathlib
import time

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dense_evolution.compiler import _compile_and_run_circuit_jit, QuantumTranspiler
from dense_evolution.gates import GATE_IDS

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_DATA_DIR = _REPO_ROOT / "data"
_IMAGES_DIR = _REPO_ROOT / "images"
_DATA_DIR.mkdir(exist_ok=True)
_IMAGES_DIR.mkdir(exist_ok=True)

jax.config.update("jax_enable_x64", True)

N_Q = 12
DIM = 2 ** N_Q
N_BONDS = N_Q - 1
N_RX = N_Q
THETA_FIXED = 1.2  # scan_ising.py's original constant -- kept, not optimized (see module docstring)

# ---------------------------------------------------------------------------
# Persistent JIT circuit: same gate structure/order as scan_ising.py's
# esegui_circuito_ising_reale, built once at module scope (see docstring).
# ---------------------------------------------------------------------------


def _build_ansatz_ops():
    ops = []
    for q in range(N_Q - 1):
        ops.append(["cx", q, q + 1])
        ops.append(["rz", q + 1, 0.0])
        ops.append(["cx", q, q + 1])
    for q in range(N_Q):
        ops.append(["rx", q, 0.0])
    return ops


def _build_template(ops):
    target = QuantumTranspiler.transpile(ops)
    rows = []
    for cmd in target:
        name = cmd[0].lower()
        g_id = float(GATE_IDS[name])
        args = cmd[1:]
        if name in ("rx", "ry", "rz", "p", "u1", "phase"):
            rows.append([g_id, float(args[0]), 0.0, -1.0])
        elif name in ("cx", "cz", "swap", "cy"):
            rows.append([g_id, float(args[0]), float(args[1]), 0.0])
        elif name in ("cp", "crz", "cphase"):
            rows.append([g_id, float(args[0]), float(args[1]), -1.0])
        else:
            rows.append([g_id, float(args[0]) if args else 0.0, 0.0, 0.0])
    return jnp.array(rows, dtype=jnp.float64)


_BASE_OPS = _build_ansatz_ops()
_TEMPLATE = _build_template(_BASE_OPS)
N_PARAMS = int(jnp.sum(_TEMPLATE[:, 3] == -1.0))  # 23: 11 rz + 12 rx, in appearance order


def _patch_and_run(single_params, init_sv):
    def patch_and_apply(carry, op):
        idx = carry
        is_param = op[3] == -1.0
        final_p = jnp.where(is_param, single_params[idx], op[3])
        next_idx = jnp.where(is_param, idx + jnp.int32(1), idx)
        return next_idx, jnp.array([op[0], op[1], op[2], final_p], dtype=jnp.float64)

    _, patched_ops = jax.lax.scan(patch_and_apply, jnp.int32(0), _TEMPLATE)
    return _compile_and_run_circuit_jit(init_sv, patched_ops)


@jax.jit
def state_batch_jit(param_batch):
    init_sv = jnp.zeros(DIM, dtype=jnp.complex128).at[0].set(1.0)
    return jax.vmap(_patch_and_run, in_axes=(0, None))(param_batch, init_sv)


# ---------------------------------------------------------------------------
# Observables: same bit-parity/bit-flip trick as scan_ising.py's own
# calcola_vera_correlazione_zz, extended to <X> the same way vqe_jax_grad.py
# computes its XX/YY kinetic term from a raw statevector.
# ---------------------------------------------------------------------------

_IDX = np.arange(DIM)
_BOND_PARITY = np.array([
    np.where(((_IDX >> q) & 1) == ((_IDX >> (q + 1)) & 1), 1.0, -1.0)
    for q in range(N_BONDS)
])  # (N_BONDS, DIM)
_FLIP_IDX = np.array([_IDX ^ (1 << q) for q in range(N_Q)])  # (N_Q, DIM)

N_PSR_SLOTS = N_RX  # only the 12 rx gates get a PSR row -- theta is fixed, see docstring
ROWS_PER_POINT = 1 + 2 * N_PSR_SLOTS  # 25: 1 base + 2 shifts x 12 rx gates


def _energy_zz_from_states(states, g_repeated):
    probs = np.abs(states) ** 2
    zz_sum = (probs @ _BOND_PARITY.T).sum(axis=1)
    conj = np.conj(states)
    x_sum = np.zeros(states.shape[0])
    for q in range(N_Q):
        x_sum += np.real(np.sum(conj * states[:, _FLIP_IDX[q]], axis=1))
    energy = -zz_sum - g_repeated * x_sum
    return energy, zz_sum / N_BONDS, x_sum


def _build_psr_batch(phi_vec):
    n_g = phi_vec.shape[0]
    base = np.concatenate(
        [np.full((n_g, N_BONDS), THETA_FIXED), np.tile(phi_vec[:, None], (1, N_RX))], axis=1)
    rows = np.repeat(base[:, None, :], ROWS_PER_POINT, axis=1)
    for k in range(N_RX):
        slot = N_BONDS + k
        rows[:, 1 + 2 * k, slot] += np.pi / 2
        rows[:, 2 + 2 * k, slot] -= np.pi / 2
    return rows.reshape(n_g * ROWS_PER_POINT, N_PARAMS)


def energy_and_grad(phi_vec, g_vec):
    """Real energy + exact chain-rule PSR gradient dE/dphi, batched over
    every g-point in one state_batch_jit call."""
    batch = _build_psr_batch(phi_vec)
    states = np.asarray(state_batch_jit(jnp.asarray(batch)))
    n_g = phi_vec.shape[0]
    g_repeated = np.repeat(g_vec, ROWS_PER_POINT)
    e_all, zz_all, _ = _energy_zz_from_states(states, g_repeated)
    e_all = e_all.reshape(n_g, ROWS_PER_POINT)
    zz_all = zz_all.reshape(n_g, ROWS_PER_POINT)
    energy = e_all[:, 0]
    zz = zz_all[:, 0]
    shifts = e_all[:, 1:].reshape(n_g, N_RX, 2)
    grad = 0.5 * (shifts[:, :, 0] - shifts[:, :, 1]).sum(axis=1)  # all rx gates share phi 1:1
    return energy, zz, grad


def check_theta_is_inert(g_vec, phi_vec, sample=5):
    """Diagnostic: exact PSR gradient dE/dtheta at a few g-points, to
    empirically confirm claim (1) in the module docstring at run time
    (not just assert it)."""
    sample_idx = np.linspace(0, len(g_vec) - 1, sample).astype(int)
    max_abs_grad = 0.0
    for i in sample_idx:
        g = g_vec[i]
        base = np.concatenate([np.full(N_BONDS, THETA_FIXED), np.full(N_RX, phi_vec[i])])
        rows = [base]
        for k in range(N_BONDS):
            plus = base.copy(); plus[k] += np.pi / 2
            minus = base.copy(); minus[k] -= np.pi / 2
            rows.append(plus); rows.append(minus)
        rows = np.array(rows)
        states = np.asarray(state_batch_jit(jnp.asarray(rows)))
        e_all, _, _ = _energy_zz_from_states(states, np.full(len(rows), g))
        shifts = e_all[1:].reshape(N_BONDS, 2)
        grad_theta = 0.5 * (shifts[:, 0] - shifts[:, 1]).sum()
        max_abs_grad = max(max_abs_grad, abs(float(grad_theta)))
    return max_abs_grad


def check_x_expectation_is_zero(phi=1.0):
    """Diagnostic: sum_q <X_q> for the ansatz at a representative phi,
    confirming claim (2) in the module docstring."""
    base = np.concatenate([np.full(N_BONDS, THETA_FIXED), np.full(N_RX, phi)])[None, :]
    sv = np.asarray(state_batch_jit(jnp.asarray(base)))
    _, _, x_sum = _energy_zz_from_states(sv, np.array([0.0]))
    return float(x_sum[0])


def optimize_vqe(g_vec, n_epochs=70, lr=0.3, beta1=0.9, beta2=0.999, eps=1e-8, verbose=True):
    n_g = len(g_vec)
    phi = 0.6 * g_vec.copy()  # same heuristic starting guess scan_ising.py hardcoded
    m = np.zeros(n_g)
    v = np.zeros(n_g)

    t0 = time.perf_counter()
    for epoch in range(1, n_epochs + 1):
        energy, zz, grad = energy_and_grad(phi, g_vec)
        m = beta1 * m + (1 - beta1) * grad
        v = beta2 * v + (1 - beta2) * grad ** 2
        m_hat = m / (1 - beta1 ** epoch)
        v_hat = v / (1 - beta2 ** epoch)
        phi -= lr * m_hat / (np.sqrt(v_hat) + eps)

        if verbose and (epoch % 10 == 0 or epoch == 1 or epoch == n_epochs):
            print(f"Epoch {epoch:03d}/{n_epochs} | mean|grad|: {np.mean(np.abs(grad)):.6f} "
                  f"| mean E: {energy.mean():+.6f} | elapsed: {time.perf_counter()-t0:.1f}s")

    energy_final, zz_final, grad_final = energy_and_grad(phi, g_vec)
    return phi, energy_final, zz_final, grad_final


def _run_full_sweep():
    print("=" * 60)
    print("ISING VQE: GENUINELY VARIATIONAL (theta, phi) OPTIMIZATION")
    print("=" * 60)

    n_g = 200  # see README/docstring: reduced from scan_ising.py's 3500 --
    # each point costs 25 forward passes of a 4096-dim circuit per Adam
    # epoch (vs. scan_ising.py's single fixed-parameter evaluation), so
    # 200 points x 70 epochs already takes ~20 minutes on this machine;
    # 200 points is far more than enough to resolve a smooth exact-diagonalization
    # susceptibility peak, and (per the docstring finding) the "optimized"
    # curve turns out to carry no g-dependence to resolve at all.
    g_vec = np.linspace(0.0, 2.5, n_g)

    print("\n--- Diagnostic: confirming theta is a dead parameter, <X> == 0 ---")
    max_theta_grad = check_theta_is_inert(g_vec, 0.6 * g_vec)
    x_check = check_x_expectation_is_zero(phi=1.0)
    print(f"max|dE/dtheta| over sampled g-points: {max_theta_grad:.3e} (expected ~0)")
    print(f"sum_q <X_q> at theta=1.2, phi=1.0: {x_check:.3e} (expected ~0)")

    print("\n--- Adam optimization of phi (theta fixed, provably inert) ---")
    t0 = time.perf_counter()
    phi_star, E_vqe, zz_vqe, grad_final = optimize_vqe(g_vec)
    t_vqe = time.perf_counter() - t0

    print("\n--- Fixed ansatz (scan_ising.py), recomputed on the same g-grid ---")
    import importlib.util
    import sys

    def _import_script(name):
        path = _REPO_ROOT / "scripts" / f"{name}.py"
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module

    scan_ising = _import_script("scan_ising")
    zz_fixed = np.empty(n_g)
    E_fixed = np.empty(n_g)
    for i, g in enumerate(g_vec):
        prob = scan_ising.esegui_circuito_ising_reale(g)
        zz_fixed[i] = scan_ising.calcola_vera_correlazione_zz(prob)
    fixed_batch = np.concatenate(
        [np.full((n_g, N_BONDS), THETA_FIXED), np.tile((0.6 * g_vec)[:, None], (1, N_RX))], axis=1)
    fixed_states = np.asarray(state_batch_jit(jnp.asarray(fixed_batch)))
    E_fixed, _, _ = _energy_zz_from_states(fixed_states, g_vec)

    print("\n--- Exact ground state (Lanczos), recomputed on the same g-grid ---")
    exact_ver = _import_script("ising_exact_verification")
    zz_sum_op, x_sum_op = exact_ver._build_operators()
    zz_exact = np.empty(n_g)
    E_exact = np.empty(n_g)
    t0 = time.perf_counter()
    for i, g in enumerate(g_vec):
        zz_exact[i], E_exact[i] = exact_ver.ground_state_zz(g, zz_sum_op, x_sum_op)
        if (i + 1) % 50 == 0:
            print(f"  exact diagonalization {i+1}/{n_g}")
    t_exact = time.perf_counter() - t0

    susc_vqe = -np.gradient(zz_vqe, g_vec)
    susc_fixed = -np.gradient(zz_fixed, g_vec)
    susc_exact = -np.gradient(zz_exact, g_vec)
    g_crit_vqe = g_vec[np.argmax(susc_vqe)]
    g_crit_fixed = g_vec[np.argmax(susc_fixed)]
    g_crit_exact = g_vec[np.argmax(susc_exact)]

    gap_vqe = E_vqe - E_exact
    gap_fixed = E_fixed - E_exact

    df = pd.DataFrame({
        "Campo_g": g_vec,
        "Phi_star": phi_star,
        "VQE_Energy": E_vqe,
        "VQE_ZZ": zz_vqe,
        "VQE_Grad_Final": grad_final,
        "Fixed_Energy": E_fixed,
        "Fixed_ZZ": zz_fixed,
        "Exact_Energy": E_exact,
        "Exact_ZZ": zz_exact,
        "Gap_VQE_minus_Exact": gap_vqe,
        "Gap_Fixed_minus_Exact": gap_fixed,
        "Susceptibility_VQE": susc_vqe,
        "Susceptibility_Fixed": susc_fixed,
        "Susceptibility_Exact": susc_exact,
    })
    csv_path = _DATA_DIR / "scan_ising_vqe.csv"
    df.to_csv(csv_path, index=False)

    plt.style.use("dark_background")
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(10, 11), sharex=True)

    ax1.plot(g_vec, zz_fixed, color="#FF007F", linewidth=1.8, linestyle="--", label=f"Fixed ansatz (g_crit~{g_crit_fixed:.3f})")
    ax1.plot(g_vec, zz_vqe, color="#00FFFF", linewidth=2.2, label="Optimized VQE (phi*(g), theta fixed)")
    ax1.plot(g_vec, zz_exact, color="#00FF7F", linewidth=2.2, label=f"Exact ground state (g_crit~{g_crit_exact:.3f})")
    ax1.set_ylabel("<ZZ>", color="#888888")
    ax1.set_ylim(-0.05, 1.05)
    ax1.grid(True, linestyle="--", alpha=0.2, color="#444444")
    ax1.legend(loc="upper right", fontsize=8)
    ax1.set_title("TFIM (N=12, open BC): fixed vs. genuinely-optimized ansatz vs. exact", fontsize=11, fontweight="bold", pad=15)

    ax2.plot(g_vec, susc_fixed, color="#FF007F", linewidth=1.6, linestyle="--", label="Fixed ansatz susceptibility")
    ax2.plot(g_vec, susc_vqe, color="#00FFFF", linewidth=1.8, label="Optimized VQE susceptibility")
    ax2.plot(g_vec, susc_exact, color="#00FF7F", linewidth=1.8, label="Exact susceptibility")
    ax2.axvline(g_crit_fixed, color="#FF007F", linestyle=":", alpha=0.8)
    ax2.axvline(g_crit_vqe, color="#00FFFF", linestyle=":", alpha=0.8)
    ax2.axvline(g_crit_exact, color="#00FF7F", linestyle=":", alpha=0.8)
    ax2.set_ylabel("Susceptibility", color="#888888")
    ax2.grid(True, linestyle="--", alpha=0.2, color="#444444")
    ax2.legend(loc="upper right", fontsize=8)

    ax3.plot(g_vec, gap_fixed, color="#FF007F", linewidth=1.6, linestyle="--", label="Fixed ansatz energy gap (E - E_exact)")
    ax3.plot(g_vec, gap_vqe, color="#00FFFF", linewidth=2.0, label="Optimized VQE energy gap (E - E_exact)")
    ax3.set_xlabel("Transverse Field Strength (g)", color="#888888")
    ax3.set_ylabel("Energy Gap", color="#888888")
    ax3.grid(True, linestyle="--", alpha=0.2, color="#444444")
    ax3.legend(loc="upper left", fontsize=8)

    plt.tight_layout()
    png_path = _IMAGES_DIR / "scan_ising_vqe.png"
    plt.savefig(png_path, dpi=300)

    print("\n" + "=" * 60)
    print(f"VQE optimization time: {t_vqe:.1f}s | Exact diagonalization time: {t_exact:.1f}s")
    print(f"Fixed ansatz critical point (crossover artifact): g = {g_crit_fixed:.4f}")
    print(f"Optimized VQE 'critical point' (susceptibility ~flat, see below): g = {g_crit_vqe:.4f}")
    print(f"Exact critical point: g = {g_crit_exact:.4f}")
    print(f"VQE <ZZ> range: [{zz_vqe.min():.6f}, {zz_vqe.max():.6f}] (theory: constant at 1.0, see docstring)")
    print(f"Energy gap (VQE - exact)  at g=0.0/0.86/1.31/2.5: "
          f"{np.interp(0.0, g_vec, gap_vqe):+.4f} / {np.interp(0.86, g_vec, gap_vqe):+.4f} / "
          f"{np.interp(1.309, g_vec, gap_vqe):+.4f} / {np.interp(2.5, g_vec, gap_vqe):+.4f}")
    print(f"Energy gap (fixed - exact) at g=0.0/0.86/1.31/2.5: "
          f"{np.interp(0.0, g_vec, gap_fixed):+.4f} / {np.interp(0.86, g_vec, gap_fixed):+.4f} / "
          f"{np.interp(1.309, g_vec, gap_fixed):+.4f} / {np.interp(2.5, g_vec, gap_fixed):+.4f}")
    print("=" * 60)
    print(f"CSV saved to {csv_path}")
    print(f"Plot saved to {png_path}")


if __name__ == "__main__":
    _run_full_sweep()
