"""
Steane code [[7,1,3]] -- block 1: encode, verify, syndrome-decode, correct.

Encoding circuit
-----------------
CSS(C1, C2) construction where C1 is the classical Hamming [7,4,3] code
(16 codewords, null space of H below) and C2 is its dual, the [7,3,4]
simplex code generated BY H's rows (8 codewords) -- C2 subset C1 is
exactly the "dual-containing" property that makes the Steane code work.
|0>_L is the uniform superposition over C2's 8 codewords, NOT over all 16
codewords of C1 (an earlier version of this script superposed over all
16, which is actually (|0>_L + |1>_L)/sqrt(2): C1 = C2 union (C2 + 1),
where 1 = 1111111 is itself a codeword of C1 but not of C2, so summing
over all of C1 mixes both logical values -- caught by the <Z_L> = 0
check below on the first run, not assumed correct).

    H = [0 0 0 1 1 1 1]   r1
        [0 1 1 0 0 1 1]   r2
        [1 0 1 0 1 0 1]   r3

Using 1-indexed qubit labels c1..c7 (0-indexed q0..q6): columns 4, 2, 1
of H are exactly e1, e2, e3 (an identity submatrix), so c4, c2, c1
(0-indexed q3, q1, q0) are a systematic set of 3 free/information qubits
for C2, and the other 4 are CNOT-derived from them:

    c3 = c1 (+) c2            c5 = c1 (+) c4
    c6 = c2 (+) c4             c7 = c1 (+) c2 (+) c4

Putting q0, q1, q3 into an equal H superposition and CNOT-deriving
q2, q4, q5, q6 from them produces exactly (1/sqrt(8)) * sum over C2's 8
codewords -- |0>_L. This matches the X-stabilizers given below
column-for-column (verified directly, not just asserted): row 1 of H is
IIIXXXX, row 2 is IXXIIXX, row 3 is XIXIXIX.

|1>_L is obtained by applying the logical X (X on all 7 qubits, i.e. XOR
with 1111111) to |0>_L -- 1111111 is a codeword of C1 but not of C2
(verified: no combination of r1/r2/r3 sums to it), so this maps C2's
coset to the other coset of C2 within C1, the correct construction for
the orthogonal logical-1 subspace.

Syndrome extraction
--------------------
This first pass uses direct expectation-value syndrome computation
(pauli_expectation on the full statevector) rather than ancilla-based
measurement circuits. This is legitimate here because every state this
script's syndrome ever gets computed on is a *known* Pauli string applied
to a stabilizer state, so pauli_expectation always returns an exact +-1
(not just "close to" -- verified below), the same information a real
ancilla measurement would collapse to, without needing to model the extra
ancilla qubits, CNOTs, and measurement collapse. Genuine ancilla-based
extraction (and dealing with the mid-circuit measurement collapse that
comes with it) is left for a later block once this baseline is verified.

Noise regimes
--------------
Section 4 (syndrome table + single-error correction) uses deterministic,
hand-injected single-qubit Pauli gates -- this is the right tool to
reproduce the textbook syndrome table and check the decoder's logic
against it exactly, one error at a time, with no sampling noise.

Section 5 (logical vs. physical error rate) uses NoiseModel's real
stochastic depolarizing Kraus channel applied independently to all 7
qubits at once, many trials per physical error rate p -- this is the
regime that actually stresses the distance-3 decoder (which only ever
proposes a single-qubit correction) with realistic multi-qubit error
events.
"""
import pathlib
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

sys.path.insert(0, r'C:\Users\Admin\Desktop\Dense-Evolution-main\Dense-Evolution-main')
from dense_evolution import DenseSVSimulator
from dense_evolution.observables import pauli_expectation
from dense_evolution.registry import NoiseModel
from dense_evolution.measurement import statevector_fidelity

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_DATA_DIR = _REPO_ROOT / "data"
_IMAGES_DIR = _REPO_ROOT / "images"
_DATA_DIR.mkdir(exist_ok=True)
_IMAGES_DIR.mkdir(exist_ok=True)

N_QUBITS = 7

X_STABILIZERS = ['IIIXXXX', 'IXXIIXX', 'XIXIXIX']
Z_STABILIZERS = ['IIIZZZZ', 'IZZIIZZ', 'ZIZIZIZ']
LOGICAL_X = 'XXXXXXX'
LOGICAL_Z = 'ZZZZZZZ'

FREE_QUBITS = [0, 1, 3]               # c1, c2, c4 -- systematic info qubits for C2
DERIVED_QUBITS = {                    # derived qubit -> free qubits it XORs (mod 2)
    2: [0, 1],                        # c3 = c1 + c2
    4: [0, 3],                        # c5 = c1 + c4
    5: [1, 3],                        # c6 = c2 + c4
    6: [0, 1, 3],                     # c7 = c1 + c2 + c4
}

FID_TOL = 1e-9


# ─────────────────────────────────────────────────────────────────────────
# Encoding
# ─────────────────────────────────────────────────────────────────────────

def encode_logical_zero() -> np.ndarray:
    sim = DenseSVSimulator(N_QUBITS)
    ops = [('h', q) for q in FREE_QUBITS]
    for derived_q, sources in DERIVED_QUBITS.items():
        for src in sources:
            ops.append(('cx', src, derived_q))
    sim.run_circuit(ops)
    return sim.get_statevector()


def apply_logical_x(sv: np.ndarray) -> np.ndarray:
    sim = DenseSVSimulator(N_QUBITS)
    sim.set_initial_state(sv)
    sim.run_circuit([('x', q) for q in range(N_QUBITS)])
    return sim.get_statevector()


def apply_single_pauli(sv: np.ndarray, gate: str, qubit: int) -> np.ndarray:
    sim = DenseSVSimulator(N_QUBITS)
    sim.set_initial_state(sv)
    sim.run_circuit([(gate, qubit)])
    return sim.get_statevector()


# ─────────────────────────────────────────────────────────────────────────
# Stabilizer / syndrome machinery
# ─────────────────────────────────────────────────────────────────────────

def check_stabilizers(sv: np.ndarray, label: str) -> bool:
    print(f"-- stabilizer check: {label} --")
    all_ok = True
    for g in X_STABILIZERS + Z_STABILIZERS:
        val = pauli_expectation(sv, g)
        ok = abs(val - 1.0) < FID_TOL
        all_ok = all_ok and ok
        print(f"   <{g}> = {val:+.9f}  {'OK' if ok else 'FAIL'}")
    return all_ok


def compute_syndrome(sv: np.ndarray, stabilizers) -> tuple:
    """3-bit syndrome: bit i = 0 if <stabilizers[i]> = +1, else 1."""
    bits = []
    for g in stabilizers:
        val = pauli_expectation(sv, g)
        assert abs(abs(val) - 1.0) < 1e-6, f"non +-1 stabilizer expectation {val} for {g}"
        bits.append(0 if val > 0 else 1)
    return tuple(bits)


def build_syndrome_table(sv0: np.ndarray) -> dict:
    """Empirical qubit -> X-stabilizer-syndrome table, built by injecting
    a single Z error on |0>_L at each qubit in turn and reading off the
    resulting syndrome. Inverted below into syndrome -> qubit for decoding."""
    qubit_to_syndrome = {}
    for q in range(N_QUBITS):
        sv_err = apply_single_pauli(sv0, 'z', q)
        qubit_to_syndrome[q] = compute_syndrome(sv_err, X_STABILIZERS)
    return qubit_to_syndrome


def _apply_pauli_string(sv: np.ndarray, pauli_str: str) -> np.ndarray:
    """Return P|psi> for Pauli string P, same index/phase convention as
    dense_evolution.observables.pauli_expectation (mirrors its internals,
    just returning the transformed vector instead of the inner product)."""
    n = int(np.log2(len(sv)))
    terms = {q: p for q, p in enumerate(pauli_str) if p != 'I'}
    dim = len(sv)

    def bit_pos(q):
        return n - 1 - q

    flip_mask = 0
    for q, p in terms.items():
        if p in ('X', 'Y'):
            flip_mask |= (1 << bit_pos(q))

    indices = np.arange(dim)
    source_idx = indices ^ flip_mask
    coeff = np.ones(dim, dtype=np.complex128)
    for q, p in terms.items():
        bit = (source_idx >> bit_pos(q)) & 1
        if p == 'Y':
            coeff = coeff * np.where(bit == 0, 1j, -1j)
        elif p == 'Z':
            coeff = coeff * np.where(bit == 0, 1.0, -1.0)
    return sv[source_idx] * coeff


def measure_stabilizer(sv: np.ndarray, pauli_str: str, rng: np.random.Generator):
    """Real projective (Born-rule) measurement of a Pauli-string stabilizer,
    with state collapse -- used for step 5, where NoiseModel's stochastic
    depolarizing channel (applied to a genuinely superposed/entangled
    encoded state) does NOT generally leave the state as an exact +-1
    eigenstate of every generator (verified directly: raw pauli_expectation
    values after NoiseModel.apply_to_sv came out as e.g. 0.75, not +-1,
    because apply_to_sv draws an independent fire/no-fire decision per
    computational-basis amplitude pair rather than one decision for the
    whole trial -- physically correct for a single deterministic Pauli
    error, not for this channel on a superposed state). Sections 3-4 use
    the cheaper compute_syndrome() directly since every state fed to it
    there IS an exact eigenstate by construction (single deterministic
    Pauli-string error on a stabilizer state).

    Returns (bit, collapsed_sv).
    """
    val = pauli_expectation(sv, pauli_str)
    p_plus = np.clip((1.0 + val) / 2.0, 0.0, 1.0)
    outcome = 1 if rng.random() < p_plus else -1
    p_sv = _apply_pauli_string(sv, pauli_str)
    collapsed = sv + outcome * p_sv
    norm = np.linalg.norm(collapsed)
    collapsed = collapsed / norm
    bit = 0 if outcome == 1 else 1
    return bit, collapsed


def extract_syndrome_with_collapse(sv: np.ndarray, stabilizers, rng: np.random.Generator):
    bits = []
    for g in stabilizers:
        bit, sv = measure_stabilizer(sv, g, rng)
        bits.append(bit)
    return tuple(bits), sv


# ─────────────────────────────────────────────────────────────────────────
# Decoding / correction
# ─────────────────────────────────────────────────────────────────────────

def decode_and_correct(sv_noisy: np.ndarray, syndrome_to_qubit: dict) -> np.ndarray:
    synd_x = compute_syndrome(sv_noisy, X_STABILIZERS)   # nonzero -> a Z error occurred
    synd_z = compute_syndrome(sv_noisy, Z_STABILIZERS)   # nonzero -> an X error occurred

    z_err_qubit = syndrome_to_qubit.get(synd_x) if synd_x != (0, 0, 0) else None
    x_err_qubit = syndrome_to_qubit.get(synd_z) if synd_z != (0, 0, 0) else None

    correction_ops = []
    if x_err_qubit is not None:
        correction_ops.append(('x', x_err_qubit))
    if z_err_qubit is not None:
        correction_ops.append(('z', z_err_qubit))

    if not correction_ops:
        return sv_noisy

    sim = DenseSVSimulator(N_QUBITS)
    sim.set_initial_state(sv_noisy)
    sim.run_circuit(correction_ops)
    return sim.get_statevector()


def decode_and_correct_stochastic(sv_noisy: np.ndarray, syndrome_to_qubit: dict, rng: np.random.Generator) -> np.ndarray:
    """Same decoder logic as decode_and_correct, but syndrome extraction
    is a real projective measurement + collapse of all 6 generators (see
    measure_stabilizer's docstring for why this is needed here and not in
    sections 3-4)."""
    synd_x, sv = extract_syndrome_with_collapse(sv_noisy, X_STABILIZERS, rng)
    synd_z, sv = extract_syndrome_with_collapse(sv, Z_STABILIZERS, rng)

    z_err_qubit = syndrome_to_qubit.get(synd_x) if synd_x != (0, 0, 0) else None
    x_err_qubit = syndrome_to_qubit.get(synd_z) if synd_z != (0, 0, 0) else None

    correction_ops = []
    if x_err_qubit is not None:
        correction_ops.append(('x', x_err_qubit))
    if z_err_qubit is not None:
        correction_ops.append(('z', z_err_qubit))

    if not correction_ops:
        return sv

    sim = DenseSVSimulator(N_QUBITS)
    sim.set_initial_state(sv)
    sim.run_circuit(correction_ops)
    return sim.get_statevector()


# ─────────────────────────────────────────────────────────────────────────
# Main verification + experiments
# ─────────────────────────────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("STEP 1-2: encoding + stabilizer verification")
    print("=" * 70)

    sv0 = encode_logical_zero()
    ok0 = check_stabilizers(sv0, '|0>_L')

    sv1 = apply_logical_x(sv0)
    ok1 = check_stabilizers(sv1, 'X_L |0>_L (candidate |1>_L)')

    z0 = pauli_expectation(sv0, LOGICAL_Z)
    z1 = pauli_expectation(sv1, LOGICAL_Z)
    x_flip_ok = abs(z0 - 1.0) < FID_TOL and abs(z1 - (-1.0)) < FID_TOL

    print(f"\n<Z_L> on |0>_L = {z0:+.9f} (expect +1)")
    print(f"<Z_L> on X_L|0>_L = {z1:+.9f} (expect -1)")
    print(f"Logical X_L correctly flips the logical qubit while staying in the code space: {x_flip_ok and ok1}")

    all_stabilizers_ok = ok0 and ok1 and x_flip_ok
    print(f"\nALL STABILIZER / LOGICAL-OPERATOR CHECKS PASSED: {all_stabilizers_ok}")
    if not all_stabilizers_ok:
        raise RuntimeError("Steane encoding circuit is WRONG -- stabilizers do not check out. Stopping.")

    print("\n" + "=" * 70)
    print("STEP 3-4: syndrome table + 21 single-qubit-error correction cases")
    print("=" * 70)

    qubit_to_syndrome_x = build_syndrome_table(sv0)
    syndrome_to_qubit = {s: q for q, s in qubit_to_syndrome_x.items()}
    assert len(syndrome_to_qubit) == N_QUBITS, "syndrome table is not a bijection over 7 qubits"

    print("Empirical qubit -> X-stabilizer-syndrome table (Z-error localization):")
    for q in range(N_QUBITS):
        print(f"   qubit {q}: syndrome {qubit_to_syndrome_x[q]}")

    # Cross-check: the identical table, built independently from X errors
    # read out via the Z-stabilizers, must match exactly (CSS self-duality
    # of the Steane code's H matrix -- same qubit sets, same order, for
    # both stabilizer families).
    qubit_to_syndrome_z = {}
    for q in range(N_QUBITS):
        sv_err = apply_single_pauli(sv0, 'x', q)
        qubit_to_syndrome_z[q] = compute_syndrome(sv_err, Z_STABILIZERS)
    tables_match = qubit_to_syndrome_x == qubit_to_syndrome_z
    print(f"X-error-via-Z-stabilizers table matches Z-error-via-X-stabilizers table: {tables_match}")
    if not tables_match:
        raise RuntimeError("Syndrome tables for X vs Z stabilizers disagree -- decoder logic is broken.")

    results = []
    n_correct = 0
    for q in range(N_QUBITS):
        for err in ('x', 'y', 'z'):
            sv_err = apply_single_pauli(sv0, err, q)
            synd_x = compute_syndrome(sv_err, X_STABILIZERS)
            synd_z = compute_syndrome(sv_err, Z_STABILIZERS)

            detected_z_qubit = syndrome_to_qubit.get(synd_x) if synd_x != (0, 0, 0) else None
            detected_x_qubit = syndrome_to_qubit.get(synd_z) if synd_z != (0, 0, 0) else None

            if err == 'x':
                located_ok = detected_x_qubit == q and detected_z_qubit is None
            elif err == 'z':
                located_ok = detected_z_qubit == q and detected_x_qubit is None
            else:  # y
                located_ok = detected_x_qubit == q and detected_z_qubit == q

            sv_corrected = decode_and_correct(sv_err, syndrome_to_qubit)
            fidelity = statevector_fidelity(sv_corrected, sv0)
            correction_ok = located_ok and abs(fidelity - 1.0) < 1e-6
            n_correct += int(correction_ok)

            results.append(dict(qubit=q, error=err.upper(), synd_x=str(synd_x), synd_z=str(synd_z),
                                 detected_x_qubit=detected_x_qubit, detected_z_qubit=detected_z_qubit,
                                 located_ok=located_ok, fidelity_after_correction=fidelity,
                                 correction_ok=correction_ok))
            status = "OK" if correction_ok else "FAIL"
            print(f"   qubit {q} error {err.upper()}: synd_X={synd_x} synd_Z={synd_z} "
                  f"-> located X@{detected_x_qubit} Z@{detected_z_qubit} | "
                  f"fidelity after correction = {fidelity:.9f}  [{status}]")

    print(f"\n{n_correct}/21 single-qubit-error cases correctly localized AND corrected to fidelity 1.0")
    all_21_ok = n_correct == 21
    if not all_21_ok:
        raise RuntimeError("Not all 21 single-error syndrome/correction cases passed. Stopping before the noise sweep.")

    df_syndrome = pd.DataFrame(results)
    syndrome_csv = _DATA_DIR / "steane_syndrome_table.csv"
    df_syndrome.to_csv(syndrome_csv, index=False)
    print(f"Syndrome table saved to {syndrome_csv}")

    print("\n" + "=" * 70)
    print("STEP 5: stochastic depolarizing noise sweep -- logical vs physical error rate")
    print("=" * 70)
    print("NOTE: NoiseModel.apply_to_sv's depolarizing channel draws an independent")
    print("fire/no-fire decision per computational-basis amplitude pair for the target")
    print("qubit, not one decision per trial -- on a genuinely superposed/entangled")
    print("state like the encoded logical qubit here, that generally leaves the state")
    print("NOT an exact stabilizer eigenstate (verified: raw <G> came out ~0.75, not")
    print("+-1). This sweep therefore uses real projective (Born-rule) syndrome")
    print("measurement with state collapse (measure_stabilizer/extract_syndrome_with_")
    print("collapse), not the raw-expectation-sign shortcut used in steps 3-4.")

    p_values = np.concatenate([
        np.linspace(0.001, 0.02, 6),
        np.linspace(0.03, 0.15, 9),
    ])
    n_trials = 4000
    rng = np.random.default_rng(1234)

    logical_error_rate = np.zeros_like(p_values)
    logical_error_stderr = np.zeros_like(p_values)

    for i, p in enumerate(p_values):
        n_logical_errors = 0
        for _ in range(n_trials):
            sv_noisy = NoiseModel.apply_to_sv(sv0.copy(), N_QUBITS, 'depolarizing', float(p), rng=rng)
            sv_corrected = decode_and_correct_stochastic(sv_noisy, syndrome_to_qubit, rng)
            fidelity = statevector_fidelity(sv_corrected, sv0)
            if fidelity < 1.0 - 1e-6:
                n_logical_errors += 1
        rate = n_logical_errors / n_trials
        logical_error_rate[i] = rate
        logical_error_stderr[i] = np.sqrt(max(rate * (1 - rate), 0.0) / n_trials)
        print(f"   p={p:.4f}: logical error rate = {rate:.5f} +- {logical_error_stderr[i]:.5f} "
              f"({n_logical_errors}/{n_trials})")

    df_sweep = pd.DataFrame({
        "physical_error_rate_p": p_values,
        "logical_error_rate": logical_error_rate,
        "logical_error_stderr": logical_error_stderr,
        "baseline_physical_rate": p_values,  # uncorrected single qubit's own error rate = p by definition
    })
    sweep_csv = _DATA_DIR / "steane_logical_vs_physical_error_rate.csv"
    df_sweep.to_csv(sweep_csv, index=False)

    below = logical_error_rate < p_values
    if below.any() and (~below).any():
        # crossover: last p where code still helps, before the trend flips
        crossover_idx = np.where(~below)[0]
        crossover_p = p_values[crossover_idx[0]] if len(crossover_idx) else None
        helps_msg = (f"Code helps (logical < physical) for p up to ~{p_values[below][-1]:.4f}; "
                     f"crosses over to hurting around p ~ {crossover_p:.4f}.")
    elif below.all():
        helps_msg = f"Code helps (logical < physical) across the ENTIRE tested range up to p={p_values[-1]:.4f}; no crossover observed in this range."
    else:
        helps_msg = f"Code does NOT help anywhere in the tested range [{p_values[0]:.4f}, {p_values[-1]:.4f}] -- logical error rate >= physical rate throughout."
    print(f"\n{helps_msg}")

    # ── plot ────────────────────────────────────────────────────────────
    plt.style.use('dark_background')
    fig, ax = plt.subplots(figsize=(9, 6.5))
    ax.errorbar(p_values, logical_error_rate, yerr=logical_error_stderr, fmt='o-',
                color='#00FFFF', linewidth=1.8, markersize=4, capsize=3, label='Steane [[7,1,3]] logical error rate')
    ax.plot(p_values, p_values, '--', color='#FF007F', linewidth=1.6, label='Baseline: uncorrected single physical qubit (rate = p)')
    ax.set_xlabel('Physical depolarizing error rate p', color='#888888')
    ax.set_ylabel('Logical error rate', color='#888888')
    ax.set_title('Steane code [[7,1,3]]: logical vs physical error rate\n(depolarizing noise, single-error syndrome decoder)',
                 fontsize=11, fontweight='bold')
    ax.grid(True, linestyle='--', alpha=0.2, color='#444444')
    ax.legend(loc='upper left', fontsize=9)
    plt.tight_layout()
    png_path = _IMAGES_DIR / "steane_logical_vs_physical_error_rate.png"
    plt.savefig(png_path, dpi=300)

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"6/6 stabilizers OK on |0>_L: {ok0}")
    print(f"6/6 stabilizers OK on X_L|0>_L: {ok1}")
    print(f"Logical X_L flips Z_L eigenvalue +1 -> -1 while staying in code space: {x_flip_ok}")
    print(f"21/21 single-qubit-error syndrome+correction cases passed: {all_21_ok}")
    print(helps_msg)
    print(f"Syndrome table CSV: {syndrome_csv}")
    print(f"Sweep CSV: {sweep_csv}")
    print(f"Plot: {png_path}")


if __name__ == "__main__":
    main()
