# -*- coding: utf-8 -*-
"""tao + cosh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjHQiPa_xYEUbKU1Q-gqS7lYeXZFXlOp
"""

# ============================================================
# Tao, cosh, entanglement: Z₂ come struttura comune
# Versione finale — Cantor in aritmetica intera esatta
# ============================================================

!pip install -q dense-evolution

import numpy as np
import matplotlib.pyplot as plt
import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)

import dense_evolution as de
from dense_evolution.noise import NoiseModel

np.random.seed(42)
print("Setup completo\n")


# ============================================================
# PARTE 1 — Probabilità di Z₂ in spazi generici
# ============================================================

def random_polygon(n_vertices, grid=20):
    pts = set()
    while len(pts) < n_vertices:
        pts.add((np.random.randint(0, grid), np.random.randint(0, grid)))
    return np.array(sorted(pts))

def has_specular_symmetry(poly):
    cx = poly[:, 0].mean()
    reflected = np.round(np.stack([2*cx - poly[:, 0], poly[:, 1]], axis=1)).astype(int)
    return set(map(tuple, poly)) == set(map(tuple, reflected))

N_trials = 5000
hits_A = sum(1 for _ in range(N_trials)
             if has_specular_symmetry(random_polygon(np.random.randint(3, 8))))
print(f"[Misura A] Poligoni casuali: P(Z₂ speculare) = {hits_A/N_trials:.5f}")


def random_fourier_func(n_modes=10, n_samples=200):
    x = np.linspace(-np.pi, np.pi, n_samples)
    f = np.zeros_like(x)
    for k in range(1, n_modes + 1):
        f += np.random.normal(0, 1)*np.cos(k*x) + np.random.normal(0, 1)*np.sin(k*x)
    return x, f

def is_even(x, f, tol=1e-6):
    return np.allclose(f, np.interp(-x, x, f), atol=tol)

hits_B = sum(1 for _ in range(N_trials) if is_even(*random_fourier_func()))
print(f"[Misura B] Funzioni di Fourier: P(Z₂ pari)   = {hits_B/N_trials:.5f}")


X = np.array([[0, 1], [1, 0]], dtype=complex)
Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.diag([1, -1]).astype(complex)
I2 = np.eye(2, dtype=complex)
XX = np.kron(X, X)

def random_2qubit_state():
    sv = np.random.normal(0, 1, 4) + 1j*np.random.normal(0, 1, 4)
    return sv / np.linalg.norm(sv)

def is_plus_one_eig(sv, tol=1e-8):
    return np.linalg.norm(XX @ sv - sv) < tol

hits_C = sum(1 for _ in range(N_trials) if is_plus_one_eig(random_2qubit_state()))
print(f"[Misura C] Stati 2-qubit casuali: P(Z₂)      = {hits_C/N_trials:.5f}\n")


# ============================================================
# PARTE 2 — Z₂ per costruzione + rumore
# ============================================================

print("=" * 60)
print("PARTE 2 — Z₂ per costruzione")
print("=" * 60 + "\n")

eps = np.linspace(-5, 5, 1001)
Z_cosh = 2 * np.cosh(eps)
err_cosh = np.max(np.abs(Z_cosh - Z_cosh[::-1]))
print(f"[cosh] max|Z(ε) - Z(-ε)| = {err_cosh:.2e}")

sim = de.DenseSVSimulator(2)
sim.run_circuit_jit([("h", 0), ("cx", 0, 1)])
bell = np.asarray(sim.get_statevector())
err_bell = np.linalg.norm(XX @ bell - bell)
print(f"[Bell] ||X⊗X|Φ+⟩ - |Φ+⟩|| = {err_bell:.2e}\n")

p_noise = 0.1
N_noise_trials = 1000

paulis = {'I': I2, 'X': X, 'Y': Y, 'Z': Z}
weights = {'I': 1-p_noise, 'X': p_noise/3, 'Y': p_noise/3, 'Z': p_noise/3}

p_theory = 0.0
preserving_pairs = []
for n1, P1 in paulis.items():
    for n2, P2 in paulis.items():
        w = weights[n1] * weights[n2]
        M = np.kron(P1, P2)
        sv_test = M @ bell
        if np.linalg.norm(sv_test) < 1e-12:
            continue
        if is_plus_one_eig(sv_test, tol=1e-8):
            p_theory += w
            preserving_pairs.append(f"{n1}⊗{n2}")

print(f"[Enumerazione esatta dei 16 Pauli pair]")
print(f"        Pair che preservano Z₂ (+1): {len(preserving_pairs)}/16")
print(f"        {preserving_pairs}")
print(f"        P_teorica = {p_theory:.4f}\n")

preserved = 0
for trial in range(N_noise_trials):
    rng = np.random.default_rng(trial)
    bell_noisy = NoiseModel.apply_to_sv(bell, 2, "depolarizing", p_noise, rng=rng)
    if is_plus_one_eig(bell_noisy, tol=1e-6):
        preserved += 1

p_measured = preserved / N_noise_trials
sigma = np.sqrt(p_theory * (1 - p_theory) / N_noise_trials)
z = (p_measured - p_theory) / sigma if sigma > 1e-9 else 0.0

print(f"[Bell + rumore p={p_noise}, {N_noise_trials} trials]")
print(f"        frazione preservata: {p_measured:.4f}")
print(f"        P_teorica enumerata: {p_theory:.4f}")
print(f"        z = {z:+.2f}\n")


# ============================================================
# PARTE 3 — Cantor set in aritmetica intera esatta
# ============================================================
#
# Cantor set at level n: 2^n segments, each of length 1 in units
# of 3^-n. Start positions are integers in these units.
# Box count at scale 3^-k (k <= n): floor(a / 3^(n-k)) for each
# segment start a. This is exact integer arithmetic — no floats,
# no floor-of-float-ratio issues.
# ============================================================

def cantor_segments_int(n):
    """Cantor segments at level n, as integers scaled by 3^n.
    Level 0: [(0, 1)] — one segment of length 1 in units of 1.
    Level k: 2^k segments of length 1 in units of 3^-k.
    """
    if n == 0:
        return [(0, 1)]
    prev = cantor_segments_int(n - 1)
    out = []
    for a, b in prev:
        w = b - a
        out.append((3*a, 3*a + w))
        out.append((3*b - w, 3*b))
    return out


D_theory = np.log(2) / np.log(3)
print("=" * 60)
print("PARTE 3 — Auto-similarità: insieme di Cantor")
print("=" * 60 + "\n")
print(f"D_teorico = log(2)/log(3) = {D_theory:.4f}\n")

for n in [2, 3, 4, 5, 6, 7, 8]:
    segs = cantor_segments_int(n)
    ks = list(range(1, n + 1))
    # Exact integer box count at each scale 3^-k
    counts = []
    for k in ks:
        divisor = 3**(n - k)
        boxes = set(a // divisor for (a, b) in segs)
        counts.append(len(boxes))
    scales = [3.0**(-k) for k in ks]
    D = -np.polyfit(np.log(scales), np.log(counts), 1)[0]
    match = "✓" if counts == [2**k for k in ks] else "✗"
    print(f"[n={n}]  counts = {counts}   D = {D:.4f}  {match}")

print(f"\nD = {D_theory:.4f} esatto per ogni n ≥ 2\n")


# ============================================================
# PARTE 4 — Yin-yang: Z₂ con np.roll
# ============================================================

print("=" * 60)
print("PARTE 4 — Yin-yang: verifica Z₂")
print("=" * 60 + "\n")

N_circle = 1000
theta = np.linspace(0, 2*np.pi, N_circle, endpoint=False)
x = np.cos(theta)
y = np.sin(theta)

shift = N_circle // 2
x_shifted = np.roll(x, shift)
y_shifted = np.roll(y, shift)

err_circle = np.max(np.abs(x_shifted + x) + np.abs(y_shifted + y))
invariant_circle = err_circle < 1e-10
print(f"Cerchio: max|R(π)P - (-P)| = {err_circle:.2e}")
print(f"Cerchio è Z₂-invariante: {invariant_circle}")

theta_s = np.linspace(0, np.pi, 500, endpoint=False)
x_top = 0.5 + 0.5*np.cos(theta_s)
y_top = 0.5*np.sin(theta_s)
x_bot = -0.5 - 0.5*np.cos(theta_s)
y_bot = -0.5*np.sin(theta_s)

x_top_rot = -x_top
y_top_rot = -y_top
err_scurve = np.max(np.abs(x_top_rot - x_bot) + np.abs(y_top_rot - y_bot))
swap_scurve = err_scurve < 1e-10
print(f"\nS-curve: max|R(π)top - bottom| = {err_scurve:.2e}")
print(f"S-curve: le metà si scambiano sotto R(π): {swap_scurve}\n")


# ============================================================
# RIEPILOGO
# ============================================================

print("=" * 60)
print("RIEPILOGO")
print("=" * 60)
print(f"""
1. Probabilità di Z₂ in spazi generici:
   - Poligoni:          {hits_A/N_trials:.5f}
   - Fourier:           {hits_B/N_trials:.5f}
   - Stati casuali:     {hits_C/N_trials:.5f}
   Simmetria rara.

2. Z₂ per costruzione:
   - cosh: errore {err_cosh:.1e}
   - Bell: errore {err_bell:.1e}

3. Rumore sul Bell (p={p_noise}):
   - Enumerazione: {len(preserving_pairs)}/16 pair preservano
   - P_teorica = {p_theory:.4f}, P_misurata = {p_measured:.4f}
   - z = {z:+.2f}  → coerenti

4. Cantor set: D = {D_theory:.4f} esatto (aritmetica intera)

5. Yin-yang:
   - Cerchio Z₂-invariante: {invariant_circle}
   - Metà che si scambiano: {swap_scurve}

Cosa è stato calcolato:
   - Tao, cosh, Bell condividono Z₂
   - Z₂ è rara in spazi generici, esatta per costruzione
   - Il rumore la rompe come predetto (z={z:.2f})
   - L'auto-similarità ha dimensione frattale esatta D = {D_theory:.4f}
""")